table ProductPurchase_Diff
	lineageTag: 65ef00ac-eb3d-4429-a000-f9ccd4111a0c

	measure AvgDaysBetweenPurchases = AVERAGE('ProductPurchase_Diff'[DaysBetweenPurchases])
		lineageTag: 277e67a6-8363-4468-a63f-60b88cfebd63

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Product ID'
		lineageTag: 1fb03645-cdda-4e12-a216-f1e95afb4cfa
		summarizeBy: none
		isNameInferred
		sourceColumn: fact_sales[Product ID]

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		formatString: General Date
		lineageTag: 7eb96eb1-5594-4d4d-b11e-2dc4bcd096ba
		summarizeBy: none
		isNameInferred
		sourceColumn: fact_sales[Order Date]

		annotation SummarizationSetBy = Automatic

	column PreviousPurchaseDate
		formatString: General Date
		lineageTag: 9e1f095c-acf0-4538-b65e-72e105d8c24e
		summarizeBy: none
		isNameInferred
		sourceColumn: [PreviousPurchaseDate]

		annotation SummarizationSetBy = Automatic

	column DaysBetweenPurchases
		formatString: 0
		lineageTag: f3c08439-fad9-4acb-9bc2-4f0cc5bef36e
		summarizeBy: sum
		isNameInferred
		sourceColumn: [DaysBetweenPurchases]

		annotation SummarizationSetBy = Automatic

	partition ProductPurchase_Diff = calculated
		mode: import
		source = ```
				
				ADDCOLUMNS(
				    SUMMARIZE(
				        fact_sales, 
				        fact_sales[Product ID], 
				        fact_sales[Order Date]
				    ),
				    "PreviousPurchaseDate", 
				    CALCULATE(
				        MAX(fact_sales[Order Date]),
				        FILTER(
				            fact_sales,
				            fact_sales[Product ID] = EARLIER(fact_sales[Product ID]) &&
				            fact_sales[Order Date] < EARLIER(fact_sales[Order Date])
				        )
				    ),
				    "DaysBetweenPurchases", 
				    DATEDIFF(
				        CALCULATE(
				            MAX(fact_sales[Order Date]),
				            FILTER(
				                fact_sales,
				                fact_sales[Product ID] = EARLIER(fact_sales[Product ID]) &&
				                fact_sales[Order Date] < EARLIER(fact_sales[Order Date])
				            )
				        ),
				        fact_sales[Order Date],
				        DAY
				    )
				)
				
				```

	annotation PBI_Id = c9dd714ed99c46839a3471427f9ea61c

