{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Orders\",\"fact_sales\",\"dim_customer\",\"dim_product\",\"Calculations\",\"dim_date\",\"dim_geo\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DaxQueryView_Desktop\",\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Orders",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\pmiro\\OneDrive\\Pulpit\\Zad_G\\Superstore.xlsx\"), null, true),",
          "    Orders_Sheet = Source{[Item=\"Orders\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Orders_Sheet, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Postal Code\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "c185f0fa-b332-4a13-8467-7ad095b48192"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "fact_tbl"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "dim_tbl"
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_c9b25a96-88e3-449a-bd7a-841110b1c641",
        "fromColumn": "Product ID",
        "fromTable": "fact_sales",
        "toColumn": "Product ID",
        "toTable": "dim_product"
      },
      {
        "name": "231b012d-bab2-1731-498c-96bdfa8f28bf",
        "fromColumn": "Order Date",
        "fromTable": "fact_sales",
        "toColumn": "Date",
        "toTable": "dim_date"
      },
      {
        "name": "e0e4e530-7a9e-5ba8-da36-5d7ce6779eed",
        "fromColumn": "Customer ID",
        "fromTable": "fact_sales",
        "toColumn": "Customer ID",
        "toTable": "dim_customer"
      },
      {
        "name": "AutoDetected_aebc32a2-ad9d-41c3-99bc-762482592e36",
        "fromColumn": "GeoID",
        "fromTable": "fact_sales",
        "toColumn": "GeoID",
        "toTable": "dim_geo"
      },
      {
        "name": "e3152838-1889-8325-6e78-8473c6a3579a",
        "fromColumn": "Order Date",
        "fromTable": "ProductPurchase_Diff",
        "toColumn": "Date",
        "toTable": "dim_date"
      },
      {
        "name": "ba407830-87b2-bde0-30bb-b84cbbce7942",
        "fromColumn": "Product ID",
        "fromTable": "ProductPurchase_Diff",
        "toColumn": "Product ID",
        "toTable": "dim_product"
      },
      {
        "name": "9557e753-30a6-27c5-48a8-5ded69c43fb0",
        "fromColumn": "Customer ID",
        "fromTable": "CustomerPurchase_Diff",
        "toColumn": "Customer ID",
        "toTable": "dim_customer"
      },
      {
        "name": "a37720ec-0ce3-7fdf-58eb-f3b3196a5379",
        "fromColumn": "Order Date",
        "fromTable": "CustomerPurchase_Diff",
        "toColumn": "Date",
        "toTable": "dim_date"
      },
      {
        "name": "ebc1c38d-01e2-5855-ef55-3dbf9d4924fa",
        "fromColumn": "Customer ID",
        "fromTable": "CustomerProductFrequency",
        "toColumn": "Customer ID",
        "toTable": "dim_customer"
      }
    ],
    "sourceQueryCulture": "pl-PL",
    "tables": [
      {
        "name": "fact_sales",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Order ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f2bab8e-a1dc-4b44-8449-31d0f65c9e95",
            "sourceColumn": "Order ID",
            "summarizeBy": "none"
          },
          {
            "name": "Order Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b11c6ede-5236-4bbc-b1a8-cf4f89e70274",
            "sourceColumn": "Order Date",
            "summarizeBy": "none"
          },
          {
            "name": "Ship Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "2585b1df-a7b5-44c4-b27f-cc31444184c3",
            "sourceColumn": "Ship Date",
            "summarizeBy": "none"
          },
          {
            "name": "Ship Mode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fdc08f18-e082-4bbd-8ad9-e5fa87096d01",
            "sourceColumn": "Ship Mode",
            "summarizeBy": "none"
          },
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da726732-5f2b-4db6-b992-e396d7aca68e",
            "sourceColumn": "Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "Product ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c925350a-5735-4f40-8e4a-d85330bae40c",
            "sourceColumn": "Product ID",
            "summarizeBy": "none"
          },
          {
            "name": "Product Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "056c40f2-eeef-428f-895f-eeaf3aa1cba8",
            "sourceColumn": "Product Name",
            "summarizeBy": "none"
          },
          {
            "name": "Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3c87eb96-bb4d-489a-8931-7fe102ef98b6",
            "sourceColumn": "Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c971faca-ecf0-46b8-8730-0d31ec0bd1c8",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a2e4cd03-44a7-467b-b50f-ffe414056dfc",
            "sourceColumn": "Discount",
            "summarizeBy": "sum"
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bdaaa448-6dbb-4b58-87ee-1f0370946564",
            "sourceColumn": "Profit",
            "summarizeBy": "sum"
          },
          {
            "name": "GeoID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f4bc5da-0f42-434f-87f4-d762bb6cf6d3",
            "sourceColumn": "GeoID",
            "summarizeBy": "none"
          },
          {
            "name": "PricePerUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "DIVIDE(fact_sales[Sales], fact_sales[Quantity])"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "c6002f7e-9f26-46f4-a892-781a90846f20",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "5d21b73c-a3c0-4017-9631-72196402ed05",
        "partitions": [
          {
            "name": "fact_sales",
            "mode": "import",
            "queryGroup": "fact_tbl",
            "source": {
              "expression": [
                "let",
                "    Source = Orders,",
                "    FactSales = Table.SelectColumns(Source, {\"Order ID\", \"Order Date\", \"Ship Date\",\"Ship Mode\", \"Customer ID\", \"Product ID\",\"Product Name\",\"Postal Code\",\"City\", \"Sales\", \"Quantity\",\"Discount\", \"Profit\"}),",
                "    AddGeoID = Table.AddColumn(FactSales, \"GeoID\", each [Postal Code] & \" - \" & [City]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(AddGeoID,{{\"Order ID\", type text}, {\"Order Date\", type date}, {\"Ship Date\", type date}, {\"Ship Mode\", type text}, {\"Customer ID\", type text}, {\"Product ID\", type text}, {\"Product Name\", type text}, {\"Postal Code\", Int64.Type}, {\"Sales\", type number}, {\"Quantity\", type number}, {\"Discount\", type number}, {\"Profit\", type number}, {\"GeoID\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Postal Code\", \"City\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_customer",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e97a40a-306a-408d-8e68-61630451a356",
            "sourceColumn": "Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c59aa66-b64a-4ef0-b513-2919db49ead7",
            "sourceColumn": "Customer Name",
            "summarizeBy": "none"
          },
          {
            "name": "Segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c452666-8a89-4f17-8f03-09ec455c1616",
            "sourceColumn": "Segment",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "[Customer Decision Segment]",
            "isDataTypeInferred": true,
            "lineageTag": "11b58bea-11f4-4c4c-b946-f8bacbed10c0",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "9cb083bd-08be-40f0-a044-4474f273381c",
        "partitions": [
          {
            "name": "dim_customer",
            "mode": "import",
            "queryGroup": "dim_tbl",
            "source": {
              "expression": [
                "let",
                "    Source = Orders,",
                "    DimCustomer = Table.Distinct(Table.SelectColumns(Source, {\"Customer ID\", \"Customer Name\", \"Segment\"})),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(DimCustomer,{{\"Customer ID\", type text}, {\"Customer Name\", type text}, {\"Segment\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_product",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Product ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c69bdcfb-baaf-4146-bd11-5918c10d872f",
            "sourceColumn": "Product ID",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d2d413c-6a8a-4d85-a7a3-cb09076a443a",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Sub-Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e44c8086-e1e5-44ed-81c6-150f70525cd9",
            "sourceColumn": "Sub-Category",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7c97f0c8-1315-4c3d-ac74-bf025ff0d394",
        "partitions": [
          {
            "name": "dim_product",
            "mode": "import",
            "queryGroup": "dim_tbl",
            "source": {
              "expression": [
                "let",
                "    Source = Orders,",
                "    DimProduct = Table.Distinct(Table.SelectColumns(Source, {\"Product ID\", \"Category\", \"Sub-Category\"})),",
                "    #\"Removed Duplicates_in_ProductID\" = Table.Distinct(DimProduct, {\"Product ID\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Duplicates_in_ProductID\",{{\"Product ID\", type text}, {\"Category\", type text}, {\"Sub-Category\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calculations",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "818b2dd3-5bbe-40ea-8839-5071714aba3c",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9f41c56c-e93d-4282-83c3-2683dac060b0",
        "measures": [
          {
            "name": "Header 2",
            "expression": [
              "",
              "VAR _header_main=\"Sales Overview\"",
              "Return",
              "_header_main"
            ],
            "lineageTag": "c586bbe6-5313-400a-85ea-0b3701e43304"
          },
          {
            "name": "Profit_Total",
            "expression": "SUM(fact_sales[Profit])",
            "formatString": "#,0.00",
            "lineageTag": "00e34879-68fa-4c29-922b-ace6a06198c4"
          },
          {
            "name": "Sales_Total",
            "expression": "SUM(fact_sales[Sales])",
            "formatString": "#,0.00",
            "lineageTag": "1421aec4-9a5b-4253-a9e1-eae9dca00499"
          },
          {
            "name": "Unit_Sold",
            "expression": "SUM(fact_sales[Quantity])",
            "formatString": "#,0.00",
            "lineageTag": "69a3e274-6fc9-476c-8827-11fad2ebc30d"
          },
          {
            "name": "COGs",
            "expression": "[Sales_Total]-[Profit_Total]",
            "formatString": "#,0.00",
            "lineageTag": "6f5383b3-34cb-40d6-90ce-c4f93bc63daa"
          },
          {
            "name": "Label2",
            "expression": [
              "",
              "VAR SelectedMeasure = SELECTEDVALUE(_Main_Metrics[_Main_Metrics Order])",
              "VAR IsMonthSelected = HASONEVALUE(dim_date[Month Name Short]) ",
              "VAR result = ",
              "    SWITCH(",
              "        TRUE(),",
              "        SelectedMeasure = 0, If([Profit_Total]>[Previous Month Value],[Profit_Total],[Previous Month Value]),",
              "        SelectedMeasure = 1, If([Sales_Total]>[Previous Month Value],[Sales_Total],[Previous Month Value]),",
              "        SelectedMeasure = 2, If([Unit_Sold]>[Previous Month Value],[Unit_Sold],[Previous Month Value]),",
              "        SelectedMeasure = 3, If([COGs]>[Previous Month Value],[COGs],[Previous Month Value]),",
              "        BLANK()",
              "    )",
              "RETURN",
              "    IF(IsMonthSelected, result, [Current Month Value])"
            ],
            "formatString": "0",
            "lineageTag": "39773ba9-199d-4e22-aedf-4865dc73fa80"
          },
          {
            "name": "Label Comparison",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR _PT_current_value=[Profit_Total]",
              "VAR _PT_variance_vs_pm=[Profit_Total]-[Previous Month Value]",
              "VAR _ST_current_value=[Sales_Total]",
              "VAR _ST_variance_vs_pm=[Sales_Total]-[Previous Month Value]",
              "VAR _UT_current_value=[Unit_Sold]",
              "VAR _UT_variance_vs_pm=[Unit_Sold]-[Previous Month Value]",
              "VAR _CT_current_value=[COGs]",
              "VAR _CT_variance_vs_pm=[COGs]-[Previous Month Value]",
              "",
              "VAR SelectedMeasure = SELECTEDVALUE(_Main_Metrics[_Main_Metrics Order])",
              "VAR IsMonthSelected = HASONEVALUE(dim_date[Month Name Short]) ",
              "VAR result = ",
              "    SWITCH(",
              "        TRUE(),",
              "        SelectedMeasure = 0,  Format(_PT_current_value, \"# ##0\") & \" |Δ\" & Format(_PT_variance_vs_pm, \"# ##0\"),",
              "        SelectedMeasure = 1,  Format(_ST_current_value, \"# ##0\") & \" |Δ\" & Format(_ST_variance_vs_pm, \"# ##0\"),",
              "        SelectedMeasure = 2,  Format(_UT_current_value, \"# ##0\") & \" |Δ\" & Format(_UT_variance_vs_pm, \"# ##0\"),",
              "        SelectedMeasure = 3,  Format(_CT_current_value, \"# ##0\") & \" |Δ\" & Format(_CT_variance_vs_pm, \"# ##0\"),",
              "        BLANK()",
              "    )",
              "RETURN",
              "    IF(IsMonthSelected, result, [Current Month Value])"
            ],
            "lineageTag": "6fb00448-eb73-41eb-bf26-f80737aa48db"
          },
          {
            "name": "Profit Margin Percentage",
            "expression": [
              "",
              "VAR _TotalSales = SUM(fact_sales[Sales])",
              "VAR _TotalProfit = SUM(fact_sales[Profit])",
              "RETURN",
              "DIVIDE(_TotalProfit , _TotalSales )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "36c84a8b-8e4b-4df0-81f0-ccdd163a2cb1"
          },
          {
            "name": "YoY Profit Growth %",
            "expression": [
              "",
              "VAR _CurrentYearProfit = SUM(fact_sales[Profit])",
              "VAR _PreviousYearProfit = CALCULATE(SUM(fact_sales[Profit]), SAMEPERIODLASTYEAR(dim_date[Date]))",
              "",
              "RETURN ",
              "DIVIDE(_CurrentYearProfit - _PreviousYearProfit, _PreviousYearProfit, 0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f6da8d3e-b4e1-4784-8223-5b3885b6319a"
          },
          {
            "name": "YoY Sales Growth %",
            "expression": [
              "",
              "VAR _CurrentYearSales = SUM(fact_sales[Sales])",
              "VAR _PreviousYearSales = CALCULATE(SUM(fact_sales[Sales]), SAMEPERIODLASTYEAR(dim_date[Date]))",
              "",
              "RETURN ",
              "DIVIDE(_CurrentYearSales - _PreviousYearSales, _PreviousYearSales, 0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2e08ad93-00a7-4072-adad-317e3c8b0d85"
          },
          {
            "name": "YoY Profit % Arrow",
            "expression": [
              "",
              "",
              "VAR _upparr=UNICHAR(129129)",
              "VAR _darr=UNICHAR(129131)",
              "VAR _varperc=[YoY Profit Growth %]",
              "VAR _varnum= [YoY Profit Growth %]",
              "VAR _blank= ISBLANK([Profit_Total])",
              "return",
              "If (_blank, blank(), IF(_varnum>0, round(_varperc,2)*100 & \"% \" & _upparr,",
              "                                round(_varperc,2)*100 & \"% \" & _darr))"
            ],
            "lineageTag": "f43e0a29-43cf-4232-b535-cdcbe5952948"
          },
          {
            "name": "YoY Sales % Arrow",
            "expression": [
              "",
              "",
              "VAR _upparr=UNICHAR(129129)",
              "VAR _darr=UNICHAR(129131)",
              "VAR _varperc=[YoY Sales Growth %]",
              "VAR _varnum= [YoY Sales Growth %]",
              "VAR _blank= ISBLANK([Sales_Total])",
              "return",
              "If (_blank, blank(), IF(_varnum>0, round(_varperc,2)*100 & \"% \" & _upparr,",
              "                                round(_varperc,2)*100 & \"% \" & _darr))"
            ],
            "lineageTag": "4298fdfa-a7ff-4454-876c-6f151ee5c282"
          },
          {
            "name": "Average Days Between Purchases",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "AVERAGEX(",
              "    ADDCOLUMNS(",
              "        SUMMARIZE(fact_sales, fact_sales[Customer ID], fact_sales[Order Date]),",
              "        \"PreviousPurchaseDate\", ",
              "        CALCULATE(",
              "            MAX(fact_sales[Order Date]),",
              "            FILTER(",
              "                fact_sales,",
              "                fact_sales[Customer ID] = EARLIER(fact_sales[Customer ID]) &&",
              "                fact_sales[Order Date] < EARLIER(fact_sales[Order Date])",
              "            )",
              "        )",
              "    ),",
              "    DATEDIFF([PreviousPurchaseDate], fact_sales[Order Date], DAY)",
              ")",
              ""
            ],
            "lineageTag": "f01b9aa3-cb25-4c63-bd44-ad43eba4cd25"
          },
          {
            "name": "Average Days Between Purchases Product",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "AVERAGEX(",
              "    ADDCOLUMNS(",
              "        SUMMARIZE(fact_sales, fact_sales[Product ID], fact_sales[Order Date]),",
              "        \"PreviousPurchaseDate\", ",
              "        CALCULATE(",
              "            MAX(fact_sales[Order Date]),",
              "            FILTER(",
              "                fact_sales,",
              "                fact_sales[Product ID] = EARLIER(fact_sales[Product ID]) &&",
              "                fact_sales[Order Date] < EARLIER(fact_sales[Order Date])",
              "            )",
              "        )",
              "    ),",
              "    DATEDIFF([PreviousPurchaseDate], fact_sales[Order Date], DAY)",
              ")"
            ],
            "lineageTag": "5fac28cf-7797-4cd7-af6d-e758105ee7c8"
          },
          {
            "name": "AvgBasketValue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    SUM(fact_sales[Sales]), ",
              "    DISTINCTCOUNT(fact_sales[Order ID])",
              ")"
            ],
            "lineageTag": "e31ac631-72db-4872-8237-ff0dce586a63"
          },
          {
            "name": "Dynamic Chart Title",
            "expression": [
              "",
              "VAR SelectedMeasure = SELECTEDVALUE(_Main_Metrics[_Main_Metrics Order])",
              "VAR _result=    SWITCH(",
              "        TRUE(),",
              "        SelectedMeasure = 0, \"Total Profit Over Time\",",
              "        SelectedMeasure = 1, \"Total Sales Over Time\",",
              "        SelectedMeasure = 2, \"Total Units Sold Over Time\",",
              "        SelectedMeasure = 3, \"Total COGS Over Time\",",
              "        \"Select a measure\"",
              "    )",
              "RETURN",
              "_result"
            ],
            "lineageTag": "cbe6d473-1cec-4a3a-9e6e-6582079bf278"
          },
          {
            "name": "Previous Month Value",
            "expression": [
              "",
              "VAR SelectedMeasure = SELECTEDVALUE(_Main_Metrics[_Main_Metrics Order])",
              "VAR IsMonthSelected = HASONEVALUE(dim_date[Month Name Short]) ",
              "VAR result = ",
              "    SWITCH(",
              "        TRUE(),",
              "        SelectedMeasure = 0, CALCULATE([Profit_Total], PREVIOUSMONTH(dim_date[Date])),",
              "        SelectedMeasure = 1, CALCULATE([Sales_Total], PREVIOUSMONTH(dim_date[Date])),",
              "        SelectedMeasure = 2, CALCULATE([Unit_Sold], PREVIOUSMONTH(dim_date[Date])),",
              "        SelectedMeasure = 3, CALCULATE([COGs], PREVIOUSMONTH(dim_date[Date])),",
              "        BLANK()",
              "    )",
              "RETURN",
              "    IF(IsMonthSelected, result, BLANK())",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "b3466028-c9e5-443c-a84e-2a32702bae8e"
          },
          {
            "name": "Current Month Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR SelectedMeasure = SELECTEDVALUE(_Main_Metrics[_Main_Metrics Order])",
              "VAR IsMonthSelected = HASONEVALUE(dim_date[Month Name Short]) ",
              "VAR result = ",
              "    SWITCH(",
              "        TRUE(),",
              "        SelectedMeasure = 0, [Profit_Total],",
              "        SelectedMeasure = 1, [Sales_Total],",
              "        SelectedMeasure = 2, [Unit_Sold],",
              "        SelectedMeasure = 3, [COGs],",
              "        BLANK()",
              "    )",
              "RETURN",
              "     result"
            ],
            "lineageTag": "aa31878a-b574-4814-88b4-6f5c628a590c"
          },
          {
            "name": "Color Label",
            "expression": [
              "",
              "",
              "VAR _PT_variance_vs_pm=[Profit_Total]-[Previous Month Value]",
              "VAR _ST_variance_vs_pm=[Sales_Total]-[Previous Month Value]",
              "VAR _UT_variance_vs_pm=[Unit_Sold]-[Previous Month Value]",
              "VAR _CT_variance_vs_pm=[COGs]-[Previous Month Value]",
              "",
              "VAR SelectedMeasure = SELECTEDVALUE(_Main_Metrics[_Main_Metrics Order])",
              "VAR IsMonthSelected = HASONEVALUE(dim_date[Month Name Short]) ",
              "VAR result = ",
              "    SWITCH(",
              "        TRUE(),",
              "        SelectedMeasure = 0, If ( _PT_variance_vs_pm>0, \"Green\", \"Red\"),",
              "        SelectedMeasure = 1, If ( _ST_variance_vs_pm>0, \"Green\", \"Red\"),",
              "        SelectedMeasure = 2, If ( _UT_variance_vs_pm>0, \"Green\", \"Red\"),",
              "        SelectedMeasure = 3, If ( _CT_variance_vs_pm>0, \"Green\", \"Red\"),",
              "        BLANK()",
              "    )",
              "RETURN",
              "    IF(IsMonthSelected, result)"
            ],
            "lineageTag": "3103818d-2e7e-4edd-a65f-08f2806fdb73"
          },
          {
            "name": "Dynamic Title",
            "expression": [
              "",
              "VAR SelectedMeasure = SELECTEDVALUE(_Main_Metrics[_Main_Metrics Order])",
              "VAR _result=    SWITCH(",
              "        TRUE(),",
              "        SelectedMeasure = 0, \"Profit\",",
              "        SelectedMeasure = 1, \"Sales\",",
              "        SelectedMeasure = 2, \"Units Sold\",",
              "        SelectedMeasure = 3, \"COGS\",",
              "        \"Select a measure\"",
              "    )",
              "RETURN",
              "_result"
            ],
            "lineageTag": "e69f737a-8dc8-41bd-bf51-7b3a8f143e96"
          },
          {
            "name": "Label Profit Margin Percentage (Top3 & Bottom3)",
            "expression": [
              "",
              "VAR RankDesc =",
              "    RANKX (",
              "        ALLSELECTED ( dim_date[YYYY-MM] ),",
              "        CALCULATE ([Profit Margin Percentage] ),",
              "        ,",
              "        DESC,",
              "        DENSE",
              "    )",
              "VAR RankAsc =",
              "    RANKX ( ALLSELECTED ( dim_date[YYYY-MM] ), CALCULATE ( [Profit Margin Percentage] ),, ASC, DENSE )",
              "RETURN",
              "  IF (",
              "        NOT ISBLANK ( [Profit Margin Percentage] ) && ( ( RankDesc <= 3 || RankAsc <= 4 ) ),",
              "        [Profit Margin Percentage],",
              "        BLANK ()",
              "    )",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "37e9cea6-0919-4045-bb21-f01faa830ffb"
          },
          {
            "name": "Label Color (Top3 & Bottom3)",
            "expression": [
              "",
              "VAR RankDesc =",
              "    RANKX (",
              "        ALLSELECTED ( dim_date[YYYY-MM] ),",
              "        CALCULATE ( [Profit Margin Percentage] ),",
              "        ,",
              "        DESC,",
              "        DENSE",
              "    )",
              "VAR RankAsc =",
              "    RANKX ( ALLSELECTED ( dim_date[YYYY-MM] ), CALCULATE ( [Profit Margin Percentage] ),, ASC, DENSE )",
              "RETURN",
              "    IF (",
              "        RankDesc <= 3,",
              "        \"#A1C197\",",
              "        // zielony dla TOP 3",
              "        IF (",
              "            RankAsc <= 4,",
              "            \"#FF404A\",",
              "            // czerwony dla BOTTOM 3",
              "            \"#000000\" // czarny (domyślny)",
              "        )",
              "    )",
              ""
            ],
            "lineageTag": "e365a0a3-a662-4124-b696-2b141073d3e9"
          },
          {
            "name": "Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SUM ( fact_sales[Sales] )"
            ],
            "lineageTag": "f2cd431b-d401-4932-acda-664a0be152e4"
          },
          {
            "name": "Revenue YoY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE (",
              "    [Revenue],",
              "    SAMEPERIODLASTYEAR ( dim_date[Date] )",
              ")"
            ],
            "lineageTag": "84dcfbd9-d107-47e7-8978-ee3ef75bd275"
          },
          {
            "name": "Revenue YoY %",
            "expression": [
              "",
              "DIVIDE ( [Revenue] - [Revenue YoY], [Revenue YoY] )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "981d4963-3378-4302-983b-4658bd220e85"
          },
          {
            "name": "Revenue per Customer",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE (",
              "    [Revenue],",
              "    DISTINCTCOUNT ( fact_sales[Customer ID] )",
              ")"
            ],
            "lineageTag": "3511ae0e-ae66-4a39-8d02-84d353c2078b"
          },
          {
            "name": "Margin per Customer",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE (",
              "    [Profit_Total],",
              "    DISTINCTCOUNT ( fact_sales[Customer ID] )",
              ")"
            ],
            "lineageTag": "0c9174f5-e5ac-40cf-8a0f-4c3d3f85ef4f"
          },
          {
            "name": "Avg Price / Unit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE ( [Revenue], [Unit_Sold] )"
            ],
            "lineageTag": "c2920b25-affd-4c69-b520-00a8dc6b3942"
          },
          {
            "name": "Avg Cost / Unit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE ( [COGs], [Unit_Sold] )"
            ],
            "lineageTag": "3052b46a-e3f1-469f-8e46-21687db07859"
          },
          {
            "name": "Profit / Unit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE ( [Profit_Total], [Unit_Sold] )"
            ],
            "lineageTag": "c085bed1-68a3-4017-8d19-5dba089ecdca"
          },
          {
            "name": "Min Revenue (Dynamic)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE (",
              "    [Revenue],",
              "    ALL ( fact_sales[Customer ID] )",
              ")",
              "* 0.005",
              ""
            ],
            "lineageTag": "a2ca0802-636a-46d1-984f-20e75d1014f3"
          },
          {
            "name": "Target Margin (Dynamic)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "0.35",
            "lineageTag": "49bc6070-41e9-401f-8a47-e8757aa32e1e"
          },
          {
            "name": "Above MinRevenue Flag",
            "expression": [
              "",
              "IF ( [Revenue] >= [Min Revenue (Dynamic)], 1, 0 )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "226dc601-5dbc-4d37-9a7b-490dea76a405"
          },
          {
            "name": "Customer Decision Segment",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    [Profit_Total] <= 0, \"EXIT\",",
              "    [Revenue] >= [Min Revenue (Dynamic)]",
              "        && [Profit Margin Percentage] < [Target Margin (Dynamic)], \"FIX PROFIT\",",
              "    [Revenue] >= [Min Revenue (Dynamic)]",
              "        && [Profit Margin Percentage] >= [Target Margin (Dynamic)], \"SCALE\",",
              "    [Revenue] < [Min Revenue (Dynamic)]",
              "        && [Profit Margin Percentage] >= [Target Margin (Dynamic)], \"GROW\",",
              "    \"IGNORE\"",
              ")",
              ""
            ],
            "lineageTag": "b66415c7-5b00-41c7-a072-06ada5e55016"
          },
          {
            "name": "Positive Profit Flag",
            "expression": [
              "",
              "IF ( [Profit_Total] > 0, 1, 0 )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "055d21cb-f791-4140-afc1-e409113c95d9"
          },
          {
            "name": "Customer Margin %",
            "expression": [
              "",
              "CALCULATE ( [Profit Margin Percentage], REMOVEFILTERS ( dim_product ) )",
              "",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c7bbff60-082a-4823-be55-47e300b33cbb"
          },
          {
            "name": "Margin Lift vs Customer (pp)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "( [Profit Margin Percentage] - [Customer Margin %] ) * 100",
              ""
            ],
            "lineageTag": "cf431a96-f91c-4551-9279-55e24ba52cd0"
          },
          {
            "name": "Fix Profit Product Flag",
            "expression": [
              "",
              "IF ( [Profit Margin Percentage] < [Target Margin (Dynamic)] && [Revenue] > 0, 1, 0 )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "0ac06d5f-f16e-4590-affe-d597a73a6ae9"
          },
          {
            "name": "Better Mix Product Flag",
            "expression": [
              "",
              "IF ( [Margin Lift vs Customer (pp)] >= 5 && [Revenue] > 0, 1, 0 )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "392dfe34-2d69-4a5e-926d-70f28260b9bd"
          },
          {
            "name": "Company Product Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE ( [Revenue], ALL ( fact_sales[Customer ID] ) )"
            ],
            "lineageTag": "3829a3cd-e77c-4d6a-a447-c10c02b8b8af"
          },
          {
            "name": "Company Product Margin %",
            "expression": [
              "",
              "CALCULATE ( [Profit Margin Percentage], ALL ( fact_sales[Customer ID] ) )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0963ad6e-16d4-4188-8d55-a36ad06b08b0"
          }
        ],
        "partitions": [
          {
            "name": "Calculations",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_date",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "7059e8f3-5eef-461a-84f3-c75d3ad69bcb",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Date Integer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1c09de9b-7d5f-400e-adc2-7ae5b55f3f0e",
            "sourceColumn": "Date Integer",
            "summarizeBy": "sum"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "88746d73-f26b-4c8b-90cb-ea5465d768ca",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Year Default",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b53b2215-4fa4-45f1-ac2d-4da94535ce03",
            "sourceColumn": "Year Default",
            "summarizeBy": "none"
          },
          {
            "name": "YYYY-MM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84f1c1a8-870e-4c24-8dd2-5c0b52ef6613",
            "sourceColumn": "YYYY-MM",
            "summarizeBy": "none"
          },
          {
            "name": "Month-Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "53b3bc4f-ae13-49b4-a88d-f5995950cde1",
            "sortByColumn": "Month Of Year",
            "sourceColumn": "Month-Year",
            "summarizeBy": "none"
          },
          {
            "name": "Month Of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e2f0dd83-2b09-4205-badf-a91433c0a362",
            "sourceColumn": "Month Of Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd9b062f-6031-4d57-8631-28c67844a1bb",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "c42ec329-d314-4fbc-960c-d838dc3d0a76",
            "sortByColumn": "Month Of Year",
            "sourceColumn": "Month Name Short",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name Default",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "011b1943-7e48-4ff9-b1d5-64b29762e986",
            "sourceColumn": "Month Name Default",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b7765cf0-7d7c-47d9-81e4-347e4f7435ef",
            "sourceColumn": "Start of Month",
            "summarizeBy": "none"
          },
          {
            "name": "End of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "40cf0204-6173-469b-b395-a00b005233de",
            "sourceColumn": "End of Month",
            "summarizeBy": "none"
          },
          {
            "name": "Days in Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "09613325-e2ae-4b95-8a56-059e05dd8c8d",
            "sourceColumn": "Days in Month",
            "summarizeBy": "sum"
          },
          {
            "name": "ISO Weeknumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "34fbd914-c6e5-4d2d-ad6b-50e99d2bb160",
            "sourceColumn": "ISO Weeknumber",
            "summarizeBy": "sum"
          },
          {
            "name": "ISO Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fd01948f-461f-4364-8ceb-2889bc9919fb",
            "sourceColumn": "ISO Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Start of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "20a079f6-511c-4b8e-8a0c-21692096e467",
            "sourceColumn": "Start of Week",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3f1a0c19-8106-4e6d-8720-91fed2eedfa7",
            "sourceColumn": "Quarter Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "032762e5-9f73-452c-a435-718c510136a4",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Year-Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a464102-1912-48c0-b2f1-3f1e2e8393ee",
            "sourceColumn": "Year-Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Day Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aee92e3d-acc1-4e51-a131-afdcbdcfdb0e",
            "sourceColumn": "Day Name",
            "summarizeBy": "none"
          },
          {
            "name": "Day Name Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "4a3e2eb2-9d2a-4d05-99fb-6cbb9bf867aa",
            "sortByColumn": "Day of Week Number",
            "sourceColumn": "Day Name Short",
            "summarizeBy": "none"
          },
          {
            "name": "Day of Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9507e729-8c0c-4318-b27b-0ae9d8987184",
            "sourceColumn": "Day of Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Day of Week Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6684aee2-402e-49e8-9ebf-53a951e6c865",
            "sourceColumn": "Day of Week Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Day of Year Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9357d6df-50cc-4549-8290-fab8d1fb756b",
            "sourceColumn": "Day of Year Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Day Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "64fd3b58-7d77-4fd9-a2c9-fdf819a5c6b9",
            "sourceColumn": "Day Offset",
            "summarizeBy": "sum"
          },
          {
            "name": "Week Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0e6bd73e-df7d-406b-8440-4d9c27d970da",
            "sourceColumn": "Week Offset",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c8c55a8e-1756-4127-9662-f27cbe7916b8",
            "sourceColumn": "Month Offset",
            "summarizeBy": "sum"
          },
          {
            "name": "Quarter Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "39d28114-555c-4956-8648-bf1e1d358343",
            "sourceColumn": "Quarter Offset",
            "summarizeBy": "sum"
          },
          {
            "name": "Year Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4b70d9fa-6344-447a-b262-ce8a84752e4d",
            "sourceColumn": "Year Offset",
            "summarizeBy": "sum"
          },
          {
            "name": "Is Weekend",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4f13d88f-85ca-4605-abb1-0c9408d4fb58",
            "sourceColumn": "Is Weekend",
            "summarizeBy": "sum"
          },
          {
            "name": "Is Weekday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "764608a5-05d6-4941-88ba-a843d4c7fa39",
            "sourceColumn": "Is Weekday",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "7057d5f2-5aa6-4585-aa22-d6ce3a93adc8",
        "partitions": [
          {
            "name": "dim_date",
            "mode": "import",
            "queryGroup": "dim_tbl",
            "source": {
              "expression": [
                "let",
                "    Today = Date.From( DateTime.LocalNow() ),",
                "    StartDate = #date(2011, 1, 1),",
                "    EndDate = Date.EndOfYear( #date(2014, 12, 31) ),",
                "    #\"List of Dates\" = List.Dates( StartDate, Duration.Days( EndDate - StartDate ) +1, #duration( 1, 0, 0, 0 ) ),",
                "    #\"Converted to Table\" = Table.FromList( #\"List of Dates\", Splitter.SplitByNothing(), type table[Date = Date.Type] ),",
                "    #\"Insert Date Integer\" = Table.AddColumn(#\"Converted to Table\", \"Date Integer\", each Number.From( Date.ToText( [Date], \"yyyyMMdd\" ) ), Int64.Type ),",
                "    #\"Insert Year\" = Table.AddColumn(#\"Insert Date Integer\", \"Year\", each Date.Year([Date]), Int64.Type),",
                "    // Creates a dynamic year value called 'Current' that moves with the current date. Put this value in a slicer and it automatically switches to the Current period.",
                "    #\"Add Year Default\" = Table.AddColumn(#\"Insert Year\", \"Year Default\", each if Date.Year( Today ) = [Year] then \"Current\" else Text.From( [Year] ), type text),",
                "    #\"Insert YYYY-MM\" = Table.AddColumn(#\"Add Year Default\", \"YYYY-MM\", each Date.ToText( [Date], \"yyyy-MM\"), type text),",
                "    #\"Insert Month-Year\" = Table.AddColumn(#\"Insert YYYY-MM\", \"Month-Year\", each Date.ToText( [Date], \"MMM yyyy\"), type text),",
                "    #\"Insert Month Number\" = Table.AddColumn(#\"Insert Month-Year\", \"Month Of Year\", each Date.Month([Date]), Int64.Type),",
                "    #\"Insert Month Name\" = Table.AddColumn(#\"Insert Month Number\", \"Month Name\", each Date.MonthName([Date], \"EN-us\"), type text),",
                "    #\"Insert Month Name Short\" = Table.AddColumn(#\"Insert Month Name\", \"Month Name Short\", each Date.ToText( [Date] , \"MMM\", \"EN-us\" ), type text),",
                "    // Creates a dynamic year value called 'Current' that moves with the current date. Put this value in a slicer and it automatically switches to the current period.",
                "    #\"Add Month Name Default\" = Table.AddColumn(#\"Insert Month Name Short\", \"Month Name Default\", each if Date.Month( Today ) = [Month Of Year] then \"Current\" else [Month Name], type text ),",
                "    #\"Insert Start of Month\" = Table.AddColumn(#\"Add Month Name Default\", \"Start of Month\", each Date.StartOfMonth([Date]), type date),",
                "    #\"Inserted End of Month\" = Table.AddColumn(#\"Insert Start of Month\", \"End of Month\", each Date.EndOfMonth( [Date] ), type date),",
                "    #\"Inserted Days in Month\" = Table.AddColumn(#\"Inserted End of Month\", \"Days in Month\", each Date.DaysInMonth([Date]), Int64.Type),",
                "    #\"Add ISO Week\" = Table.AddColumn(#\"Inserted Days in Month\", \"ISO Weeknumber\", each let",
                "   CurrentThursday = Date.AddDays([Date], 3 - Date.DayOfWeek([Date], Day.Monday ) ),",
                "   YearCurrThursday = Date.Year( CurrentThursday ),",
                "   FirstThursdayOfYear = Date.AddDays(#date( YearCurrThursday,1,7),- Date.DayOfWeek(#date(YearCurrThursday,1,1), Day.Friday) ),",
                "   ISO_Week = Duration.Days( CurrentThursday - FirstThursdayOfYear) / 7 + 1",
                "in ISO_Week, Int64.Type ),",
                "    #\"Add ISO Year\" = Table.AddColumn(#\"Add ISO Week\", \"ISO Year\", each Date.Year(  Date.AddDays( [Date], 26 - [ISO Weeknumber] ) ), Int64.Type ),",
                "    #\"Insert Start of Week\" = Table.AddColumn(#\"Add ISO Year\", \"Start of Week\", each Date.StartOfWeek([Date], Day.Monday ), type date),",
                "    #\"Insert Quarter Number\" = Table.AddColumn(#\"Insert Start of Week\", \"Quarter Number\", each Date.QuarterOfYear([Date]), Int64.Type),",
                "    #\"Added Quarter\" = Table.AddColumn(#\"Insert Quarter Number\", \"Quarter\", each \"Q\" & Text.From( Date.QuarterOfYear([Date]) ), type text ),",
                "    #\"Add Year-Quarter\" = Table.AddColumn(#\"Added Quarter\", \"Year-Quarter\", each Text.From( Date.Year([Date]) ) & \"-Q\" & Text.From( Date.QuarterOfYear([Date]) ), type text ),",
                "    #\"Insert Day Name\" = Table.AddColumn(#\"Add Year-Quarter\", \"Day Name\", each Date.DayOfWeekName([Date], \"EN-us\" ), type text),",
                "    #\"Insert Day Name Short\" = Table.AddColumn( #\"Insert Day Name\", \"Day Name Short\", each Date.ToText( [Date], \"ddd\", \"EN-us\" ), type text),",
                "    #\"Insert Day of Month Number\" = Table.AddColumn(#\"Insert Day Name Short\", \"Day of Month Number\", each Date.Day([Date]), Int64.Type),",
                "    // Day.Monday indicates the week starts on Monday. Change this in case you want the week to start on a different date. ",
                "    #\"Insert Day of Week\" = Table.AddColumn(#\"Insert Day of Month Number\", \"Day of Week Number\", each Date.DayOfWeek( [Date], Day.Monday ), Int64.Type),",
                "    #\"Insert Day of Year\" = Table.AddColumn(#\"Insert Day of Week\", \"Day of Year Number\", each Date.DayOfYear( [Date] ), Int64.Type),",
                "    #\"Add Day Offset\" = Table.AddColumn(#\"Insert Day of Year\", \"Day Offset\", each Number.From( Date.From( Today ) - [Date] ) , Int64.Type ),",
                "    #\"Add Week Offset\" = Table.AddColumn(#\"Add Day Offset\", \"Week Offset\", each Duration.Days( Date.StartOfWeek( [Date], Day.Monday ) - Date.StartOfWeek( Today, Day.Monday ) ) / 7 , Int64.Type ),",
                "    #\"Add Month Offset\" = Table.AddColumn(#\"Add Week Offset\", \"Month Offset\", each ( [Year] - Date.Year( Today ) ) * 12 + ( [Month Of Year] - Date.Month( Today ) ), Int64.Type ),",
                "    #\"Add Quarter Offset\" = Table.AddColumn(#\"Add Month Offset\", \"Quarter Offset\", each ( [Year] - Date.Year(Today) ) * 4 + Date.QuarterOfYear( [Date] ) - Date.QuarterOfYear( Today ), Int64.Type ),",
                "    #\"Add Year Offset\" = Table.AddColumn(#\"Add Quarter Offset\", \"Year Offset\", each [Year] - Date.Year(Today), Int64.Type ),",
                "    #\"Insert Is Weekend\" = Table.AddColumn(#\"Add Year Offset\", \"Is Weekend\", each if Date.DayOfWeek( [Date] ) >= 5 then 1 else 0, Int64.Type ),",
                "    #\"Insert Is Weekday\" = Table.AddColumn(#\"Insert Is Weekend\", \"Is Weekday\", each if Date.DayOfWeek( [Date] ) < 5 then 1 else 0, Int64.Type )",
                "in",
                "    #\"Insert Is Weekday\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_geo",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Postal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1c152b78-f122-43c4-b110-8c451416a745",
            "sourceColumn": "Postal Code",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "City",
            "dataType": "string",
            "lineageTag": "f7a42e5b-ed4f-471e-bbf0-0d4b001c6eab",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "StateOrProvince",
            "dataType": "string",
            "lineageTag": "59fc86b6-a170-4c28-9afa-47e3f683c523",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "805a2695-9809-4438-8866-a60fcebabf57",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Country",
            "dataType": "string",
            "lineageTag": "9702e1de-bc6e-4a04-90c3-759d4646c890",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "GeoID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39affc8f-6be2-407b-808c-d4f5d051fbb3",
            "sourceColumn": "GeoID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "dd0c87ff-5b31-4df9-811c-a92eacc708d0",
        "partitions": [
          {
            "name": "dim_geo",
            "mode": "import",
            "queryGroup": "dim_tbl",
            "source": {
              "expression": [
                "let",
                "    Source = Orders,",
                "    SelectedColumns = Table.SelectColumns(Source, {\"Postal Code\", \"City\",\"State\", \"Region\", \"Country\"}),",
                "    AddGeoID = Table.AddColumn(SelectedColumns, \"GeoID\", each [Postal Code] & \" - \" & [City]),",
                "    RemovedDuplicates = Table.Distinct(AddGeoID),",
                "    SortedTable = Table.Sort(RemovedDuplicates,{{\"Postal Code\", Order.Ascending}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(SortedTable,{{\"City\", type text}, {\"State\", type text}, {\"Region\", type text}, {\"Country\", type text}, {\"Postal Code\", Int64.Type}, {\"GeoID\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Prod_Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "6ab0464806fd4e2c8f6c814a6e9332c5"
          }
        ],
        "columns": [
          {
            "name": "_Prod_Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "6b3c344a-4937-41d0-b4ed-56fe7c66d2b4",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "_Prod_Parameter Fields"
                }
              ]
            },
            "sortByColumn": "_Prod_Parameter Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "_Prod_Parameter Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "324edb2a-0920-4bc2-bb12-391b175936be",
            "sortByColumn": "_Prod_Parameter Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "_Prod_Parameter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "cfc7c95d-4e61-49dd-92aa-33147592ae0e",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "4c4f8be8-8ed9-44d6-ae3c-e9c57ba84e46",
        "partitions": [
          {
            "name": "_Prod_Parameter",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Category\", NAMEOF('dim_product'[Category]), 0),",
                "    (\"Sub-Category\", NAMEOF('dim_product'[Sub-Category]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "_Main_Metrics",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "4265994774e34af0b08de675789471da"
          }
        ],
        "columns": [
          {
            "name": "_Main_Metrics",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "407786ee-570b-4787-b703-2dadcb4cf58e",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "_Main_Metrics Fields"
                }
              ]
            },
            "sortByColumn": "_Main_Metrics Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "_Main_Metrics Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "540d9e12-aec7-45be-afe6-2c41604a1761",
            "sortByColumn": "_Main_Metrics Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "_Main_Metrics Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "a0dba503-a12c-4031-8832-b4a634e015ef",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "fd953a11-0309-4f34-b33f-a6667b56a3bf",
        "measures": [
          {
            "name": "BIM Info",
            "expression": [
              "",
              "VAR TableInfo =",
              "    ADDCOLUMNS (",
              "        INFO.VIEW.TABLES (),",
              "        \"Component\", \"Tables\"",
              "    )",
              "VAR ColumnInfo =",
              "    ADDCOLUMNS (",
              "        INFO.VIEW.COLUMNS (),",
              "        \"Component\", \"Columns\"",
              "    )",
              "VAR RelationshipInfo =",
              "    ADDCOLUMNS (",
              "        INFO.VIEW.RELATIONSHIPS (),",
              "        \"Component\", \"Relationships\"",
              "    )",
              "VAR MeasureInfo =",
              "    ADDCOLUMNS (",
              "        INFO.VIEW.MEASURES (),",
              "        \"Component\", \"Measures\"",
              "    )",
              "VAR Result =",
              "    TOCSV ( TableInfo )",
              "        & TOCSV ( ColumnInfo )",
              "        & TOCSV ( RelationshipInfo )",
              "        & TOCSV ( MeasureInfo )",
              "RETURN",
              "    Result",
              "",
              "",
              "// Authored by Brian Julius, Feb 2025"
            ],
            "lineageTag": "6efc60d4-46a6-4016-9ed7-fd15b73ceb3c"
          }
        ],
        "partitions": [
          {
            "name": "_Main_Metrics",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Profit\", NAMEOF('Calculations'[Profit_Total]), 0),",
                "    (\"Sales\", NAMEOF('Calculations'[Sales_Total]), 1),",
                "    (\"Unit Sold\", NAMEOF('Calculations'[Unit_Sold]), 2),",
                "    (\"COGs\", NAMEOF('Calculations'[COGs]), 3)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "_Geo_Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "bd11efa3181e4df8b036a0ef8820ef83"
          }
        ],
        "columns": [
          {
            "name": "_Geo_Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "5872e2a4-9738-4a3a-868d-f039c8331aed",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "_Geo_Parameter Fields"
                }
              ]
            },
            "sortByColumn": "_Geo_Parameter Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "_Geo_Parameter Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "58b1c3b3-0176-48e0-9bb9-213757bd1195",
            "sortByColumn": "_Geo_Parameter Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "_Geo_Parameter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "49ee4593-5b4d-4628-88d4-eca6a48469ec",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "2b0eeb99-d525-42a3-9b94-e60cffcd6801",
        "partitions": [
          {
            "name": "_Geo_Parameter",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Region\", NAMEOF('dim_geo'[Region]), 0),",
                "    (\"State\", NAMEOF('dim_geo'[State]), 1),",
                "    (\"Country\", NAMEOF('dim_geo'[Country]), 2),",
                "    (\"City\", NAMEOF('dim_geo'[City]), 3)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "ProductPurchase_Diff",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c9dd714ed99c46839a3471427f9ea61c"
          }
        ],
        "columns": [
          {
            "name": "Product ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1fb03645-cdda-4e12-a216-f1e95afb4cfa",
            "sourceColumn": "fact_sales[Product ID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Order Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "7eb96eb1-5594-4d4d-b11e-2dc4bcd096ba",
            "sourceColumn": "fact_sales[Order Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "PreviousPurchaseDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "9e1f095c-acf0-4538-b65e-72e105d8c24e",
            "sourceColumn": "[PreviousPurchaseDate]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DaysBetweenPurchases",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f3c08439-fad9-4acb-9bc2-4f0cc5bef36e",
            "sourceColumn": "[DaysBetweenPurchases]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "65ef00ac-eb3d-4429-a000-f9ccd4111a0c",
        "measures": [
          {
            "name": "AvgDaysBetweenPurchases",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE('ProductPurchase_Diff'[DaysBetweenPurchases])",
            "lineageTag": "277e67a6-8363-4468-a63f-60b88cfebd63"
          }
        ],
        "partitions": [
          {
            "name": "ProductPurchase_Diff",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "ADDCOLUMNS(",
                "    SUMMARIZE(",
                "        fact_sales, ",
                "        fact_sales[Product ID], ",
                "        fact_sales[Order Date]",
                "    ),",
                "    \"PreviousPurchaseDate\", ",
                "    CALCULATE(",
                "        MAX(fact_sales[Order Date]),",
                "        FILTER(",
                "            fact_sales,",
                "            fact_sales[Product ID] = EARLIER(fact_sales[Product ID]) &&",
                "            fact_sales[Order Date] < EARLIER(fact_sales[Order Date])",
                "        )",
                "    ),",
                "    \"DaysBetweenPurchases\", ",
                "    DATEDIFF(",
                "        CALCULATE(",
                "            MAX(fact_sales[Order Date]),",
                "            FILTER(",
                "                fact_sales,",
                "                fact_sales[Product ID] = EARLIER(fact_sales[Product ID]) &&",
                "                fact_sales[Order Date] < EARLIER(fact_sales[Order Date])",
                "            )",
                "        ),",
                "        fact_sales[Order Date],",
                "        DAY",
                "    )",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "_ProdDetails_Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "9b55bf9d651a4bb990b1b0f813ab42d7"
          }
        ],
        "columns": [
          {
            "name": "_ProdDetails_Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "751c7a55-f4e9-4004-8349-9ea36a17a9b8",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "_ProdDetails_Parameter Fields"
                }
              ]
            },
            "sortByColumn": "_ProdDetails_Parameter Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "_ProdDetails_Parameter Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "373fec74-fe78-41ed-a341-c563460d600d",
            "sortByColumn": "_ProdDetails_Parameter Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "_ProdDetails_Parameter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "5ac1c157-e941-4d92-bb2e-a812412c565d",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "e48b74ea-7fb5-4510-b04f-e21acc15c771",
        "partitions": [
          {
            "name": "_ProdDetails_Parameter",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Sub-Category\", NAMEOF('dim_product'[Sub-Category]), 0),",
                "    (\"Product Name\", NAMEOF('fact_sales'[Product Name]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "CustomerPurchase_Diff",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "7d7e648716a14698a45763b3afcb55da"
          }
        ],
        "columns": [
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6d95665f-b042-46f7-b4ec-5162f29eb7f1",
            "sourceColumn": "fact_sales[Customer ID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Order Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8c1b5a70-5f2f-4dd2-a151-507448be477e",
            "sourceColumn": "fact_sales[Order Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "PreviousPurchaseDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a6f6271e-b350-42d3-90aa-0eafd4df2ce7",
            "sourceColumn": "[PreviousPurchaseDate]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DaysBetweenPurchases",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "7c5e2bbb-11c0-4610-a4da-8cf1610fe4cd",
            "sourceColumn": "[DaysBetweenPurchases]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "7e597f6f-ad4f-4a7b-95cb-2ec265190743",
        "measures": [
          {
            "name": "CustomerAvgDaysBetweenPurchases",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE('CustomerPurchase_Diff'[DaysBetweenPurchases])",
            "lineageTag": "c82d6592-79fa-4112-8348-b74e650e8032"
          }
        ],
        "partitions": [
          {
            "name": "CustomerPurchase_Diff",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "ADDCOLUMNS(",
                "    SUMMARIZE(",
                "        fact_sales, ",
                "        fact_sales[Customer ID], ",
                "        fact_sales[Order Date]",
                "    ),",
                "    \"PreviousPurchaseDate\", ",
                "    CALCULATE(",
                "        MAX(fact_sales[Order Date]),",
                "        FILTER(",
                "            fact_sales,",
                "            fact_sales[Customer ID] = EARLIER(fact_sales[Customer ID]) &&",
                "            fact_sales[Order Date] < EARLIER(fact_sales[Order Date])",
                "        )",
                "    ),",
                "    \"DaysBetweenPurchases\", ",
                "    DATEDIFF(",
                "        CALCULATE(",
                "            MAX(fact_sales[Order Date]),",
                "            FILTER(",
                "                fact_sales,",
                "                fact_sales[Customer ID] = EARLIER(fact_sales[Customer ID]) &&",
                "                fact_sales[Order Date] < EARLIER(fact_sales[Order Date])",
                "            )",
                "        ),",
                "        fact_sales[Order Date],",
                "        DAY",
                "    )",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "CustomerProductFrequency",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ef8813be43294ba2ab16eedb5a7338ff"
          }
        ],
        "columns": [
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "bae5b598-b5c4-4b14-8403-80803fdd0fe5",
            "sourceColumn": "fact_sales[Customer ID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "PurchaseCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0d6979e6-ce68-4429-978a-4b9277fb48f5",
            "sourceColumn": "[PurchaseCount]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "CustomerType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF([PurchaseCount] = 1, \"One-time\", \"Returning\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "7d8aad99-d681-4d01-93f1-c328c28c0d1d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "398bac9d-6c65-4f8f-af96-3419a2f721a1",
        "partitions": [
          {
            "name": "CustomerProductFrequency",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SUMMARIZE(",
                "    fact_sales,",
                "    fact_sales[Customer ID],",
                "    \"PurchaseCount\", COUNTROWS(fact_sales)",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}