//DAX QUERY – SCALE (najlepsi klienci do wzrostu)
//Tu idą handlowcy, kampanie i upsell
EVALUATE
FILTER (
    ADDCOLUMNS (
        SUMMARIZE (
            fact_sales,
            fact_sales[Customer ID]
        ),
        "Revenue", [Revenue],
        "Gross Profit", [Profit_Total],
        "Margin %", [Profit Margin Percentage],
        "Profit per Unit", [Profit / Unit],
        "MinRevenue Threshold", [Min Revenue (Dynamic)],
        "Target Margin", [Target Margin (Dynamic)]
    ),
   [Revenue] >= [Min Revenue (Dynamic)]
        && [Profit Margin Percentage] >= [Target Margin (Dynamic)]
        && [Gross Profit] > 0
)
ORDER BY [Gross Profit] DESC