EVALUATE
VAR MinProductRevenueShare = 0.002  -- 0.2% całej sprzedaży jako „skala” produktu (możesz potem zrobić parametr)
VAR TotalRevenueAll =
    CALCULATE ( [Revenue], ALL ( fact_sales[Product ID] ) )

RETURN
TOPN (
    50,
    FILTER (
        ADDCOLUMNS (
            SUMMARIZE ( fact_sales, fact_sales[Product ID] ),
            "Revenue", [Revenue],
            "Quantity", [Unit_Sold],
            "Gross Profit", [Profit_Total],
            "Margin %", [Profit Margin Percentage],
            "Profit / Unit", [Profit / Unit],
            "Revenue Share %", DIVIDE ( [Revenue], TotalRevenueAll )
        ),
        [Gross Profit] > 0
            && [Margin %] > 0
            && [Revenue Share %] >= MinProductRevenueShare
    ),
    [Gross Profit], DESC
)
